alias wip="cd ~/storage/shared/WIP"
alias coder="php -S 127.0.0.1:1028 -t ~/BLACKICEcoder/"
alias webServer="python2 -m SimpleHTTPServer 8000"
alias debian="~/debian/start-debian.sh"
alias lightSail="ssh -i [keyName].pem admin@[IP_ADDRESS]"
